"use client";

import { useEffect, useState, type FormEvent } from "react";
import { LoaderCircle, Phone, Plus, Trash2 } from "lucide-react";

type Contact = { id: string; name: string; relationship: string; phone: string };

export function ContactManager() {
  const [contacts, setContacts] = useState<Contact[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/contact").then(async (res) => { const data = await res.json(); if (!res.ok) throw new Error(data.error); setContacts(data.contacts); }).catch((err) => setError(err.message)).finally(() => setLoading(false)); }, []);
  async function addContact(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); setError(""); try { const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), relationship: form.get("relationship"), phone: form.get("phone") }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setContacts((items) => [...items, data.contact].sort((a, b) => a.name.localeCompare(b.name))); event.currentTarget.reset(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to save contact."); } finally { setSaving(false); } }
  async function remove(id: string) { if (!window.confirm("Remove this emergency contact?")) return; const response = await fetch(`/api/contact/${id}`, { method: "DELETE" }); if (response.ok) setContacts((items) => items.filter((item) => item.id !== id)); else setError("Unable to remove contact."); }
  return <div className="grid gap-6 lg:grid-cols-[.85fr_1.15fr]"><form onSubmit={addContact} className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-semibold text-navy">Add a contact</h2><div className="mt-4 space-y-3"><input required name="name" placeholder="Name" className="focus-ring w-full rounded-xl border px-3 py-2.5" /><input required name="relationship" placeholder="Relationship (e.g. Parent)" className="focus-ring w-full rounded-xl border px-3 py-2.5" /><input required name="phone" type="tel" placeholder="Phone number" className="focus-ring w-full rounded-xl border px-3 py-2.5" /></div>{error && <p className="mt-3 text-sm text-red-700">{error}</p>}<button disabled={saving} className="focus-ring mt-4 inline-flex items-center gap-2 rounded-xl bg-navy px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{saving ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}Save contact</button></form><section>{loading ? <LoaderCircle className="m-8 h-6 w-6 animate-spin text-slate-500" /> : contacts.length === 0 ? <div className="rounded-2xl border border-dashed bg-white p-8 text-center text-sm text-slate-500">No emergency contacts saved yet.</div> : <div className="space-y-3">{contacts.map((contact) => <div key={contact.id} className="flex items-center justify-between rounded-2xl border bg-white p-5 shadow-sm"><div><p className="font-semibold text-navy">{contact.name}</p><p className="text-sm text-slate-500">{contact.relationship}</p><a href={`tel:${contact.phone}`} className="mt-2 inline-flex items-center gap-1 text-sm font-medium text-sky-700"><Phone className="h-3.5 w-3.5" />{contact.phone}</a></div><button onClick={() => remove(contact.id)} className="focus-ring rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-700"><Trash2 className="h-4 w-4" /></button></div>)}</div>}</section></div>;
}
