import { Document, Page, StyleSheet, Text, View, renderToBuffer } from "@react-pdf/renderer";
import React from "react";

const styles = StyleSheet.create({ page: { padding: 36, fontSize: 11, color: "#172033", fontFamily: "Helvetica" }, brand: { fontSize: 18, fontFamily: "Helvetica-Bold", color: "#102A43" }, title: { marginTop: 18, fontSize: 22, fontFamily: "Helvetica-Bold" }, meta: { marginTop: 6, color: "#62748A" }, notice: { marginTop: 18, padding: 10, backgroundColor: "#FFF7E6", color: "#7A4B00" }, heading: { marginTop: 18, marginBottom: 6, fontSize: 13, fontFamily: "Helvetica-Bold" }, message: { marginBottom: 8, padding: 9, backgroundColor: "#F6F8FB", lineHeight: 1.4 }, role: { fontFamily: "Helvetica-Bold", marginBottom: 3 }, footer: { position: "absolute", bottom: 30, left: 36, right: 36, fontSize: 8, color: "#718096" } });

export async function createEmergencyPdf({ title, severity, location, createdAt, messages }: { title: string; severity: string; location?: string; createdAt: Date; messages: Array<{ role: string; message: string; createdAt: Date }> }) {
  const document = <Document title={`GuardianAI emergency report - ${title}`}><Page size="A4" style={styles.page}><Text style={styles.brand}>GuardianAI</Text><Text style={styles.title}>Emergency response report</Text><Text style={styles.meta}>{title} · Risk level: {severity}</Text><Text style={styles.meta}>Created {createdAt.toLocaleString()} {location ? `· Location: ${location}` : ""}</Text><View style={styles.notice}><Text>This document is a record of AI-assisted emergency guidance. It is not a medical diagnosis and does not replace professional emergency care.</Text></View><Text style={styles.heading}>Session timeline</Text>{messages.map((item, index) => <View key={index} style={styles.message}><Text style={styles.role}>{item.role === "user" ? "User" : "GuardianAI"}</Text><Text>{item.message}</Text><Text style={styles.meta}>{item.createdAt.toLocaleString()}</Text></View>)}<Text style={styles.footer}>If symptoms are severe, worsening, or life-threatening, call your local emergency number immediately.</Text></Page></Document>;
  return renderToBuffer(document);
}
